### ISSUE TITLE
[Feat] 팔로우 버튼으로 팔로잉 여부 표시 (게시글 목록에서)

### ISSUE THREAD

**Issue by choubung** [GDGoC-Sookmyung-HawaSu/2024-02-Spring-Novice-ToyProject#8]
## 📌 Task
- [x] 게시글 목록의 팔로우 버튼에 팔로잉 여부 반영 
- [x] 팔로우 중이라면 [unfollow]
- [x] 아직 팔로우하고 있지 않다면 [follow]로 표시

## 📚 Reference
-
